dx: update run-test script and expectations
Update the run-test script to use the javac from prebuilts.

Update expectations for tests that were failing locally and not on the
buildbots. It looks like these failures stem from different javac
versions.

Fix array bounds error in 127-merge-stress.

Bug: 64707326
Test: art/tools/buildbot-build.sh --host && dalvik/dx/tests/run-all-tests

Change-Id: Ibc4b9216db9fed42aee8f239775ee4cb94536b74

diff --git a/dx/tests/run-test b/dx/tests/run-test
--- a/dx/tests/run-test
+++ b/dx/tests/run-test
@@ -33,9 +33,20 @@ cd "${progdir}"
 progdir=`pwd`
 prog="${progdir}"/`basename "${prog}"`
 
-export JAVAC="${progdir}/../../../prebuilt/common/openjdk/bin/javac"
+if [[ -z "${JAVA_HOME}" ]]; then
+    unix=$(uname | tr '[A-Z]' '[a-z]')
+    JAVA_HOME="${progdir}/../../../prebuilts/jdk/jdk8/${unix}-x86"
+fi
+
+if [[ ! -d "${JAVA_HOME}" ]]; then
+    echo "Missing JAVA_HOME directory: $JAVA_HOME" 1>&2
+    exit 1
+fi
+
+export JAVAC="${JAVA_HOME}/bin/javac"
 if [ "!" -e "$JAVAC" ]; then
-    JAVAC="javac"
+    echo "Missing JAVAC executable: ${JAVAC}" 1>&2
+    exit 1
 fi
 
 info="info.txt"
